const fs = require('fs');
const path = require('path');
const pkg = require('../package.json');

const filePath = path.resolve(__dirname, '../src/version.ts');
const content = `// This file is generated by scripts/generate-version.js. Do not edit directly.
export const SDK_VERSION = "${pkg.version}";
`;

fs.writeFileSync(filePath, content, 'utf8');
console.log(`Generated ${filePath}`);
